language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - MASTER_DOMAIN=ocelot.com
  - AUTH0_KEY=null
  - AUTH0_DOMAIN=null
  - IDENTITY_SERVICE_DOMAIN=null
  - INVENTORY_SERVICE_DOMAIN=null
  - IDENTITY_SERVICE_PUBLIC_DOMAIN=null
  - INVENTORY_SERVICE_PUBLIC_DOMAIN=null
  # GEMFURY_NPM_KEY
  - secure: "TuLyzajvLZsM/OHIQUvu1vhQalyiZGxu9uRxeiLYUMeJ5hzKv4PupPW97hpAiCqzs9F9nJsRTTJBhdLZuXdIJaYg5W+Dkqh5e3E1X4356vTq5cdepiycanLtrpDbFDkBXEj1iu22pn31u24ULOX7xKGlpM5xdNg2bX36srJEIF0qLTksuPl/wIM3CnS+eaGdPhCz/0fw1PwgIbWneypV9hiz1Il6envuQ2eY5UZ6PiIx0ZsvPlq4pmGMhND6NuH4YLA08XpUnrCpHnOrMIdVUDenUr192CfCTCaNQEUAY5CqTCq9e3//84wtvqj8EhLpYuR/YRKLY4qgC8G37yCec0hP+WJBh35LGUeIfIjWnrpkak3X7P1n14IAmjYE5EuKdNsKuX9XFbWflDQl0XExBjosV3IqDMcIToYVzZ+H5ERzAguBhzcZtXL33bvDUnGdbe0zb17Dt/bBpXjjIXAdWH4wGdYt+BjZ3d5TDt7a8HEckP9AvMD1CFlcke2+nIKXdeKh5GpDDOc+3MXkZFhD5pUN+3EANYYVVKISshrU1Q3DDFLKxtvLNzEYTVAD8CLAnTEznfyUgaRnNqjgvt4EofMaBNvjtFNeQRMFsvW5FEjcQ7D8CaSEPR94DoAV9xLupim0O5mzQfOvFMSYj7FUJ7lvLx2NKvNJC1MYvwIWD38="

install:
- npm install --registry=https://npm-proxy.fury.io/vsRAKKMwEs5p1RhfMGiF/ocelot-saas/ --progress=false
- npm run build

script:
- npm run test-travis

# after_success: 
# - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
- provider: script
  skip_cleanup: true
  script: bin/togemfury.sh
- provider: heroku
  skip_cleanup: true
  app: ocelot-saas-webshop
  api_key:
    secure: "lIu1bchPKEJau0Ct3nu8Bkn5hwNFaIzwzlqj5y33xDQ4IPo7tMIry1zbtq5dLHgkOTy36lfQm32BheFqVfTXbqFL13xfMl1eDvci2uLos9wV/eXNecgI8mi+sMf8sf8YLcgEGUpetICU+mtra383dRHtjcolka38elxM7wi+9A1q3W+Yuc10mv2Q3QCLl1IGIb5C4ox25/eU02CVSrx0IHcYD4wbjvSWGS1cd1KmDirWlR4yqmtJGa+XYRMfvxRK+ob5LWjk0rlzJSskruB9zSaErgsYhOPdf2iUyKaF9ZSRK7kXYQH78zzrg901fYJjZ1hUz2g0Ur8hw9aMLQPq6HZbNyEeCdtXrx5UwLpQQjHBkFM5bmqrO3I00cW3Z3/mnRbDUMB+Oz1KFrvsN0PU8DlVahdpx+V1tdKGgRpHyFy7t0sB5Zrq0DQgN7H9r4kAJd4MZlxaVcP24+EOBRR9mKCFSkxg5CmgfN75ysG+6jZqko6Bx3XxS4FBmiA8k+MtPxf3z2MkJHpa0elG/uIN+WmTbA+GuGYBlzunDWt64GD/9f2A3iPkAdNGes+ZtfpTAYMP/2YNB+w3iAYawm0rs+P9txDDvKreI5KXwK3qE/OJXceZnn7ywu65ydXO7khtsfyJ7xfS+KT6fGh1rGGQS/1jLYG9eWN8l5xw76WQYzU="
